In [49]:
import numpy as np

In [50]:
x = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y = np.array([[1,0,1,0]])

In [51]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [52]:
def sigmderv(x):
    return x*(1-x)

In [53]:
weights = []
biases = []
num_layers = 0

In [54]:
def create_model(sizes):
    #[3,4,4,1]
    global weights;
    global biases;
    global num_layers;
    num_layers = len(sizes)
    weights = [np.random.randn(x,y)
                        for x, y in zip(sizes[:-1], sizes[1:])]
    biases = [np.random.randn(y, 1) for y in sizes[1:]]

In [55]:
create_model([3,4,4,1])

In [56]:
weights

[array([[ 0.16100142, -0.65693829, -1.08923779,  1.35234817],
        [ 0.27528499,  2.06833832,  0.70317636, -0.0494222 ],
        [-1.39786887, -0.90130607, -0.40360762, -0.39367895]]),
 array([[ 1.3142819 , -0.7618112 ,  0.26683071, -0.1260576 ],
        [-0.49595643, -0.05344883,  0.60568252, -0.22009898],
        [ 0.34805806, -0.2590417 ,  1.54720759,  1.13242332],
        [-1.26349418, -0.75339679,  0.79945277,  0.66890174]]),
 array([[ 0.41146973],
        [-3.08452393],
        [ 0.36968189],
        [-1.79884911]])]

In [57]:
activations = [x]
scores = []

In [58]:
def forwardPass():
    global weights;
    global biases;
    global activations;
    activation = x
    for w,b in zip(weights,biases):
        z = np.dot(activation,w)+b
        activation = sigmoid(z)
        activations.append(activation)
    #print(activations[-1])
        


In [59]:
for iter in range(10000):
    forwardPass()
    delta = (activations[-1]-y.T)*sigmderv(activations[-1])
    w_grads = [np.zeros(w.shape) for w in weights]
    b_grads = [np.zeros(b.shape) for b in biases]
    b_grads[-1] = delta
    w_grads[-1] = np.dot(activations[-2].T,delta)
    for layer in range(2,num_layers):
        #print(layer)
        #print("DB",delta)
        #print("weights[-layer+1].T):",weights[-layer+1].T)
        #print("activations[-layer-1]",activations[-layer-1])
        delta = np.dot(delta,weights[-layer+1].T)*sigmderv(activations[-layer])
        b_grads[-layer] = delta
        w_grads[-layer] = np.dot(activations[-layer-1].T,delta)
            
    weights = [w-dw for w,dw in zip(weights,w_grads)]
    biases = [b-db for b,db in zip(biases,b_grads)]
    
print(activations[-1])

[[0.99441112]
 [0.00377174]
 [0.99474816]
 [0.00433328]]
